name: Build and Push Base Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'stryker-agent/Dockerfile.base'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # THIS IS THE NEW, CORRECT STEP
      - name: Prepare Docker tag in lowercase
        id: prep
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lc=$REPO_LC" >> "$GITHUB_OUTPUT"

      # THIS STEP IS NOW FIXED TO USE THE OUTPUT FROM THE STEP ABOVE
      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: ./stryker-agent
          file: ./stryker-agent/Dockerfile.base
          push: true
          # This now uses the lowercase variable `repo_lc`
          tags: ghcr.io/${{ steps.prep.outputs.repo_lc }}:base-latest
