name: Build and Push Base Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'stryker-agent/Dockerfile.base'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: ./stryker-agent
          file: ./stryker-agent/Dockerfile.base
          push: true
          tags: ghcr.io/${{ github.repository }}:base-latest
          lowercase: true
