name: Build and Push Base Docker Image

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Also runs automatically if you change the base Dockerfile on the master branch
  push:
    branches:
      - master
    paths:
      - 'stryker-agent/Dockerfile.base'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Grant permissions to write to the GitHub Packages registry
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: ./stryker-agent  # The directory where your Dockerfiles are
          file: ./stryker-agent/Dockerfile.base # The specific file to build
          push: true
          tags: ghcr.io/${{ github.repository }}:base-latest
