name: AI Mutation Testing Agent

on:
  pull_request:
    branches:
      - master

jobs:
  run-ai-agent:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      # --- FIX: Add permission to read from GitHub Packages ---
      packages: read

    steps:
      - name: 1. Checkout Agent Code (from master branch)
        uses: actions/checkout@v4
        with:
          ref: 'master'
          path: 'agent_code'

      - name: 2. Checkout Feature Branch Code (to be tested)
        uses: actions/checkout@v4
        with:
          path: 'repo_to_test'

      # --- FIX: This step is now much faster ---
      - name: 3. Build and Run AI Agent
        run: |
          # This build command is now very fast. It pulls the pre-built base image
          # from GHCR and just adds the Python application code on top.
          docker build --no-cache -t stryker-agent -f ./agent_code/stryker-agent/Dockerfile ./agent_code/stryker-agent
          
          # The run command remains the same
          docker run --rm \
            -v "$(pwd)/repo_to_test":/repo \
            -e GITHUB_TOKEN="${{ secrets.GH_PAT }}" \
            -e GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}" \
            -e GITHUB_REPOSITORY="${{ github.repository }}" \
            -e PR_NUMBER="${{ github.event.number }}" \
            -e SOURCE_BRANCH="${{ github.head_ref }}" \
            stryker-agent

      - name: 4. Upload Mutation Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mutation-test-dashboard
          path: repo_to_test/mutation-dashboard.html
